envVarGroups:
  - name: pulseboard-shared
    envVars:
      - key: NODE_ENV
        value: production
      - key: ABLY_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ABLY_KEY
        sync: false
      - key: PLAUSIBLE_BASE_URL
        sync: false
      - key: PLAUSIBLE_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: OLLAMA_MODEL
        value: llama3
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: PulseBoard <hello@pulseboard.local>

services:
  - type: keyvalue
    name: pulseboard-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: pulseboard-web
    runtime: docker
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    plan: starter
    autoDeploy: true
    envVarGroups:
      - pulseboard-shared
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulseboard-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pulseboard-redis
          type: keyvalue
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DIRECT_URL
        fromDatabase:
          name: pulseboard-db
          property: connectionString
      - key: SESSION_COOKIE_NAME
        value: pulseboard.session
      - key: PUBLIC_DEFAULT_ORG_SLUG
        value: demo

  - type: worker
    name: pulseboard-worker
    runtime: docker
    dockerfilePath: ./apps/worker/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVarGroups:
      - pulseboard-shared
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulseboard-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pulseboard-redis
          type: keyvalue
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: pulseboard-db
          property: connectionString

databases:
  - name: pulseboard-db
    databaseName: pulseboard
    user: pulseboard
